[package]
name = "bigfootpp/lucid"
version = "0.3.0"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
authors = ["Bigfoot"]
description = "A lightweight LuaU package to simplify OOP"
repository = "https://github.com/Bigfootpp/lucid"
realm = "shared"
exclude = ["**"]

include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "README.md",
    "wally.toml"
]

[dependencies]

[dev-dependencies]