[package]
name = "bigfootpp/lucid"
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
authors = ["Bigfoot"]
description = "A lightweight LuaU package to simplify OOP"
repository = "https://github.com/Bigfootpp/lucid"
realm = "shared"
exclude = [
    "DevPackages",
    "Packages",
    "rblx-place",
    "tests",
    "runner",
    ".vscode",
    "aftman.toml",
    "default.project.json",
    "wally.lock"
]

[dependencies]
TableUtil = "sleitnick/table-util@1.2.1"

[dev-dependencies]